# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Scenario n. 2 - Reference - ReFuel EU
#
# | Temporal matching        | Hourly matching                           | Yes                                   |
# | Aviation sector          | Aviation demand                           | Central                               |
# |                          | e-kerosene blending mandate               | ReFuel EU                             |
# | Demand projections       | Electricity demand + EV share             | Medium                                |
# | Costs                    | Electricity generation (NREL ATB)         | Moderate + tax credits                |
# |                          | Electrolysis (ICCT IRA assumptions)       | Moderate (no tax credits)             |
# |                          | DAC                                       | Moderate  + tax credits               |
# |                          | Point-source COâ‚‚ capture (NPC)            | Conservative + tax credits            |
# | Supply constraint        | CO2 supply                                | Biogenic & non-biogenic sources + DAC |
# | Power sector development | Transmission expansion                    | No new expansion *                    |
# |                          | State policies for electricity generation | Current policies                      |
# * Optimal transmission expansion if infeasible

countries: ["US"]

enable:
  retrieve_databundle: false  #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: true
  retrieve_cost_data: true  # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: true  # If 'true', OpenStreetMap data will be downloaded for the above given countries

run:
  name: "US_scenario_02" # use this to keep track of runs with different settings
  sector_name: "US_scenario_02"

foresight: myopic

scenario:
  simpl: ['']
  ll: ['v1']
  clusters: [100]
  opts: [3H]
  planning_horizons:
  - 2030
  - 2035
  - 2040
  sopts:
  - "3H"

aviation_demand_scenario:
  country: US
  scenario: central # low, central or high

saf_mandate:
  ekerosene_split: true # separate e-kerosene as separate bus
  non_spatial_ekerosene: true # connects all e-kerosene buses with a single E-kerosene-main bus to model 0 cost of transport and store
  enable_mandate: true # enable SAF mandate
  saf_scenario: EU # EU (default), EU+, EU-

demand_projection:
  planning_horizon: 2030 # only needed for power model, sector model takes demand from UN data using planning_horizon
  scenario: "Medium"
  data_centers_load: true

policies:
  state: ["CES", "RES"] # "CES" to adopt State-wise clean electricity generation constraints from currently stated policies, "RES" to adopt State-wise renewable electricity generation constraints from currently stated policies, both to apply both kinds of constraintsAdd commentMore actions
  country: [] # "CES" to adopt country-wise clean electricity generation constraint (90% clean electricity by 2040), otherwise empty

custom_industry:
  CCS_retrofit: [ethanol, ammonia, steel, cement]

cluster_options:
  alternative_clustering: false  # "False" use Voronoi shapes, "True" use GADM shapes
  simplify_network:
    p_threshold_drop_isolated: 0.0

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, csp, geothermal, nuclear, OCGT, CCGT, biomass]
    Store: [battery, H2]

  custom_powerplants: "replace" #  "false" use only powerplantmatching (ppm) data, "merge" combines ppm and custom powerplants, "replace" use only custom powerplants

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, geothermal, biomass]
  renewable_carriers: [solar, csp, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    stats: false  # False, = greenfield expansion, 'irena' uses IRENA stats to add expansion limits

renewable:
  hydro:
    normalization:
      method: eia
    hydro_capital_cost: true

costs:
  year: 2030
  cost_scenario: "moderate" # only used if `country_specific_data: "US"`; can be "moderate", "advanced" or "conservative"
  cost_scenario_by_technology_group: # (optional): overwrites for some specific technology groups
    electricity: "moderate"
    H2_electrolysis: "moderate"
    dac: "moderate"

policy_config:
  hydrogen:
    temporal_matching: "hourly" # either "hourly", "monthly", "yearly", "no_temporal_matching"
    additionality: true
    temporal_matching_carriers: [csp, solar, onwind, offwind-ac, offwind-dc, ror, hydro, nuclear]

demand_data:
  base_year: 2021

custom_data:
  airports: true

existing_capacities:
  threshold_capacity: 5 # MW, below this threshold capacities are not added in separate horizon

sector:
  electricity_distribution_grid: true
  conventional_generation: # generator : carrier
    OCGT: gas
    CCGT: gas
    oil: oil
    coal: coal
    biomass: biomass
  hydrogen:
    production_technologies: ["Alkaline electrolyzer large", "PEM electrolyzer", "SOEC", "SMR"]

  cc: false # Default CC technologies from PyPSA-Earth (not influencing ethanol, ammonia, cement and still carbon capture retrofits
  SMR CC: false

  land_transport_fuel_cell_share:
    AB_2030: 0.0
    AB_2035: 0.0
    AB_2040: 0.0
  land_transport_electric_share:
    AB_2030: 0.165 # 0.041 (Reference) 0.165 (Medium) 0.191 (High)
    AB_2035: 0.275 # 0.053 (Reference) 0.275 (Medium) 0.332 (High)
    AB_2040: 0.353 # 0.064 (Reference) 0.353 (Medium) 0.462 (High)
  shipping_hydrogen_share:
    AB_2030: 0.00
    AB_2035: 0.00
    AB_2040: 0.00

solving:
  options:
    load_shedding: false
  solver:
    name: gurobi
    options: gurobi-default
  solver_options:
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-4
      BarHomogeneous: 1

plotting:
  tech_colors:
    PHS: #036356
    wind: #6895dd
