name: pypsa-earth-efuels
channels:
  - conda-forge
  - gurobi
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - affine=2.4.0=pyhd8ed1ab_1
  - ampl-asl=1.0.0=he0c23c2_2
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h29418f3_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - atlite=0.4.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h5e0e64b_7
  - aws-c-cal=0.9.0=hd8a8e38_1
  - aws-c-common=0.12.3=h2466b09_0
  - aws-c-compression=0.3.1=h5d0e663_5
  - aws-c-event-stream=0.5.4=h2c6ec7e_9
  - aws-c-http=0.10.1=h2d86538_1
  - aws-c-io=0.19.0=hfdfeb85_2
  - aws-c-mqtt=0.13.0=hef5cf85_3
  - aws-c-s3=0.7.17=h3b2a8e2_2
  - aws-c-sdkutils=0.2.3=h5d0e663_5
  - aws-checksums=0.2.7=h5d0e663_1
  - aws-crt-cpp=0.32.5=h5528c5b_3
  - aws-sdk-cpp=1.11.510=hf5dcd55_8
  - azure-core-cpp=1.14.0=haf5610f_0
  - azure-identity-cpp=1.10.0=hd6deed7_0
  - azure-storage-blobs-cpp=12.13.0=h3241184_1
  - azure-storage-common-cpp=12.8.0=hd6deed7_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - bottleneck=1.5.0=py310hb0944cc_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - brotli-python=1.1.0=py310h9e98ed7_3
  - brotlicffi=1.1.0.0=py310h9e98ed7_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.5=h2466b09_0
  - c-blosc2=2.15.2=h9e57077_1
  - ca-certificates=2025.10.5=h4c7d964_0
  - cachecontrol=0.14.3=pyha770c72_0
  - cachecontrol-with-filecache=0.14.3=pyhd8ed1ab_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - capnproto=1.0.2=hb5d7e06_3
  - cartopy=0.23.0=py310hb4db72f_2
  - cdsapi=0.7.6=pyhd8ed1ab_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310ha8f682b_0
  - cfgrib=0.9.15.0=pyhd8ed1ab_0
  - cfgv=3.3.1=pyhd8ed1ab_1
  - cfitsio=4.5.0=h2b45a09_0
  - cftime=1.6.4=py310hb0944cc_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - click-default-group=1.2.4=pyhd8ed1ab_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda-lock=3.0.4=pyha6a9232_1
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contextily=1.6.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - country_converter=1.3.1=pyhd8ed1ab_0
  - cpp-expected=1.1.0=hc790b64_1
  - cpython=3.10.18=py310hd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py310ha8f682b_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - datashader=0.18.2=pyhd8ed1ab_0
  - datrie=0.8.2=py310ha8f682b_8
  - debugpy=1.8.16=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=pyhd8ed1ab_5
  - distlib=0.4.0=pyhd8ed1ab_0
  - distributed=2025.7.0=pyhe01879c_0
  - docutils=0.22=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_0
  - dulwich=0.22.8=py310hc226416_0
  - earth-osm=2.3.post1=pyhd8ed1ab_0
  - eccodes=2.41.0=h4f3607b_0
  - ecmwf-datastores-client=0.4.0=pyhd8ed1ab_0
  - ensureconda=1.6.0=pyhcf101f3_0
  - entsoe-py=0.7.3=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - findlibs=0.1.2=pyhd8ed1ab_0
  - fiona=1.9.6=py310h6a2b1aa_4
  - fmt=11.1.4=h5f12afc_1
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py310hdb0e946_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.13.3=h57928b3_1
  - freexl=2.0.0=hf297d47_2
  - fribidi=1.0.10=h8d14728_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdal=3.9.3=py310h8b8bc08_19
  - geographiclib=2.0=pyhd8ed1ab_1
  - geopandas=0.14.3=pyhd8ed1ab_0
  - geopandas-base=0.14.3=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_2
  - geos=3.13.1=h9ea8674_0
  - geotiff=1.7.4=h887f4e7_0
  - geoviews=1.14.1=hd8ed1ab_0
  - geoviews-core=1.14.1=pyha770c72_0
  - getopt-win32=0.1=h6a83c73_3
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.84.1=h3d4babf_0
  - glib-tools=2.84.1=h4394cf3_0
  - glpk=5.0=h8ffe710_0
  - graphite2=1.3.14=hac47afa_2
  - graphviz=12.2.1=hf40819d_1
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - gts=0.7.6=h6b5321d_4
  - gurobi=12.0.3=py310_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.6.4=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py310h2b0be38_100
  - harfbuzz=11.2.1=h8796e6f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - holoviews=1.21.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh7428d3b_8
  - hvplot=0.12.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - identify=2.6.13=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflate64=1.0.3=py310ha8f682b_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipopt=3.14.19=h75e447d_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310h5588dad_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kealib=1.6.1=hadd4d7f_0
  - keyring=25.6.0=pyh7428d3b_0
  - kiwisolver=1.4.9=py310h1e1005b_0
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.1=cxx17_h4eb7d71_0
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.7.7=h5343c79_4
  - libarrow=20.0.0=h80a5264_3_cuda
  - libarrow-acero=20.0.0=h7d8d6a5_3_cuda
  - libarrow-dataset=20.0.0=h7d8d6a5_3_cuda
  - libarrow-substrait=20.0.0=hb76e781_3_cuda
  - libblas=3.9.0=34_h6be65bb_openblas
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=34_h2a8eebe_openblas
  - libclang13=20.1.8=default_hadf22e1_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.23=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_4
  - libgd=2.3.3=h7208af6_11
  - libgdal=3.9.3=hc25ceda_19
  - libgdal-core=3.9.3=hdc3ac45_16
  - libgdal-fits=3.9.3=h20f9414_16
  - libgdal-grib=3.9.3=h9921521_16
  - libgdal-hdf4=3.9.3=hf9aff8f_16
  - libgdal-hdf5=3.9.3=h7df419c_16
  - libgdal-jp2openjpeg=3.9.3=h768cd86_16
  - libgdal-kea=3.9.3=hfc54ade_16
  - libgdal-netcdf=3.9.3=h3717446_16
  - libgdal-pdf=3.9.3=h33ae9eb_16
  - libgdal-pg=3.9.3=h5e54256_16
  - libgdal-postgisraster=3.9.3=h5e54256_16
  - libgdal-tiledb=3.9.3=h8d6a7ae_16
  - libgdal-xls=3.9.3=hd0c044b_16
  - libglib=2.84.1=h7025463_0
  - libgomp=15.1.0=h1383e82_4
  - libgoogle-cloud=2.36.0=hf249c01_1
  - libgoogle-cloud-storage=2.36.0=he5eb982_1
  - libgrpc=1.71.0=h8c3449c_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=34_hd232482_openblas
  - liblzma=5.8.1=h2466b09_2
  - libmamba=2.2.0=h2cdc3e1_0
  - libnetcdf=4.9.2=nompi_h008f77d_116
  - libogg=1.3.5=h2466b09_1
  - libopenblas=0.3.30=openmp_h96ad2b0_2
  - libparquet=20.0.0=ha850022_3_cuda
  - libpng=1.6.50=h7351971_1
  - libpq=17.6=h063c6db_0
  - libprotobuf=5.29.3=hd33f5f0_2
  - libre2-11=2025.06.26=habfad5f_0
  - librttopo=1.1.0=hbfc9ebc_18
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.35=h8883371_0
  - libspatialindex=2.1.0=h518811d_0
  - libspatialite=5.1.0=h208f9ff_13
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.0=h797046b_4
  - libutf8proc=2.10.0=hff4702e_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - linopy=0.3.11=pyhd8ed1ab_0
  - llvm-openmp=20.1.8=hfa2b4ca_1
  - llvmlite=0.44.0=py310h0288bfe_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=6.0.0=py310h4b5876d_0
  - lz4=4.4.4=py310hd8baafb_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mamba=2.2.0=h4873d24_0
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markdown=3.8.2=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib=3.5.2=py310h5588dad_1
  - matplotlib-base=3.5.2=py310h79a7439_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - memory_profiler=0.61.0=pyhd8ed1ab_1
  - mercantile=1.2.1=pyhd8ed1ab_1
  - minizip=4.0.10=h9fa1bad_0
  - mistune=3.1.3=pyh29332c3_0
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - msgpack-python=1.1.1=py310hc19bc0b_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - multiurl=0.3.7=pyhd8ed1ab_0
  - multivolumefile=0.2.3=pyhd8ed1ab_1
  - mumps-seq=5.8.1=hea37e11_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.1.2=pyhe01879c_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py310h0a2a089_101
  - networkx=3.4=pyhd8ed1ab_0
  - nlohmann_json=3.11.3=he0c23c2_1
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.2=py310h9216ec7_1
  - numexpr=2.10.2=py310hc0c24f9_100
  - numpoly=1.2.14=pyhd8ed1ab_0
  - numpy=1.26.4=py310hf667824_0
  - openjpeg=2.5.3=h24db6dd_1
  - openpyxl=3.1.5=py310h8d17308_1
  - openssl=3.5.4=h725018a_0
  - orc=2.1.2=h35764e3_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310hb4db72f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.7.5=pyhd8ed1ab_0
  - pango=1.56.3=h0c53d3b_1
  - param=2.2.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h6d647b9_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - polars=1.32.3=default_h34cc8bc_0
  - polars-default=1.32.3=py39he906d20_0
  - poppler=24.12.0=heaa0bce_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=17.6=h8836559_0
  - powerplantmatching=0.7.1=pyhd8ed1ab_0
  - pre-commit=4.3.0=pyha770c72_0
  - progressbar2=4.5.0=pyhd8ed1ab_1
  - proj=9.5.1=h4f671f6_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - protobuf=5.29.3=py310h9e98ed7_0
  - psutil=7.0.0=py310ha8f682b_0
  - pthread-stubs=0.4=h0e40799_1002
  - pulp=2.7.0=py310h5588dad_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - py7zr=1.0.0=pyhd8ed1ab_0
  - pyarrow=20.0.0=py310h5588dad_0
  - pyarrow-core=20.0.0=py310h8b91b4e_0_cuda
  - pybcj=1.0.6=py310ha8f682b_0
  - pycountry=24.6.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pycryptodomex=3.23.0=py310ha8f682b_0
  - pyct=0.5.0=pyhd8ed1ab_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py310h034784e_0
  - pydoe2=1.3.0=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.10.0=py310h4eba6db_0
  - pyomo=6.9.3=py310h73ae2b4_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyppmd=1.1.0=py310h9e98ed7_1
  - pyproj=3.7.1=py310h19d4cff_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pypsa=0.24.0=pyhd8ed1ab_0
  - pyqt=5.15.11=py310h936fe8c_1
  - pyqt5-sip=12.17.0=py310h9e98ed7_1
  - pyreadline3=3.5.4=py310h5588dad_1
  - pyshp=3.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytables=3.10.1=py310h961c5d5_4
  - pytest=8.4.1=pyhd8ed1ab_0
  - python=3.10.18=h8c5b53a_0_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-eccodes=2.37.0=py310hb0944cc_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.10.18=hd8ed1ab_0
  - python-installer=0.7.0=pyhff2d567_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-utils=3.9.1=pyhff2d567_1
  - python_abi=3.10=8_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyviz_comms=3.0.6=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_0
  - pywin32-ctypes=0.2.3=py310h5588dad_2
  - pywinpty=2.0.15=py310h9e98ed7_0
  - pyyaml=6.0.2=py310h38315fa_2
  - pyzmq=27.0.1=py310h49f0f51_0
  - pyzstd=0.17.0=py310he5e10e1_0
  - qt-main=5.15.15=h9151539_4
  - rasterio=1.3.11=py310h9a640ac_2
  - re2=2025.06.26=h3dd2b4f_0
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=h2466b09_0
  - reproc-cpp=14.2.5.post0=he0c23c2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - reverse-geocode=1.4.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rioxarray=0.18.1=pyhd8ed1ab_0
  - rpds-py=0.27.0=py310h034784e_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruamel.yaml=0.17.26=py310h8d17308_0
  - ruamel.yaml.clib=0.2.8=py310ha8f682b_1
  - scikit-learn=1.7.1=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - semver=3.0.4=pyhd8ed1ab_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py310hb052cae_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - simdjson=3.13.0=hc790b64_0
  - sip=6.10.0=py310h9e98ed7_0
  - six=1.17.0=pyhe01879c_1
  - smart_open=7.3.0.post1=pyhe01879c_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - spdlog=1.15.3=ha881ca7_0
  - sqlite=3.50.4=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310h8f3aa81_0
  - stopit=1.1.2=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tblib=3.1.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tiledb=2.27.2=hfef3e3b_7
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tomlkit=0.13.3=pyha770c72_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - toposort=1.10=pyhd8ed1ab_1
  - tornado=6.5.2=py310h29418f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trove-classifiers=2025.9.11.17=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=h57928b3_1
  - ukkonen=1.0.1=py310hc19bc0b_5
  - unicodedata2=16.0.0=py310ha8f682b_0
  - unidecode=1.3.8=pyh29332c3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - validators=0.35.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - virtualenv=20.34.0=pyhd8ed1ab_0
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py310h29418f3_0
  - xarray=2023.11.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=he0c23c2_2
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libice=1.1.2=h0e40799_0
  - xorg-libsm=1.2.6=h0e40799_0
  - xorg-libx11=1.8.12=hf48077a_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xorg-libxext=1.3.6=h0e40799_0
  - xorg-libxpm=3.5.17=h0e40799_1
  - xorg-libxt=1.3.1=h0e40799_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - yaml-cpp=0.8.0=he0c23c2_0
  - yte=1.8.1=pyha770c72_0
  - zeromq=4.3.5=ha9f60a1_7
  - zict=3.0.0=pyhd8ed1ab_1
  - zipfile-deflate64=0.2.0=py310h8d17308_4
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.2.5=h1608b31_0
  - zstandard=0.23.0=py310ha8f682b_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - chaospy==4.3.20
      - currencyconverter==0.18.9
      - fake-useragent==2.2.0
      - googledrivedownloader==1.1.0
      - highspy==1.11.0
      - plotly==6.3.0
      - tsam==2.3.9
prefix: C:\Users\Yerbol\miniconda3\envs\pypsa-earth-stable
